### ISSUE TITLE
crop size and difference between cudnn and cuda-convnet

### ISSUE THREAD

**Issue by soheilb** [uoguelph-mlrg/theano_alexnet#20]
I have a wired issue. When I am using the crop size of 227 for the images, as done in the script, I can train the network using both cudnn and cuda-convent libraries. However, when I change the crop size to 224 (and corresponding input size to 224 in the alex_net.py file), I can only run the training using cudna-copnvent library and the cudnn implementation does not work. Can any of the contributors help me on this?

**Comment by gwding** [comment]
@soheilb could you paste the error message here? and which lines you were making changes?

**Comment by soheilb** [comment]
My changes are in the lines 37 and 45 of the alex_net.py file where I changed 227 to 224 (to make it exactly equal to the alexnet paper). Then I used the config file to select between cudnn and cuda-convnet (lib_conv flag). The error seems to be relevant to the size of the input for the first fully connected layer. Apparently using cudnn, the input size of the first fully connected layer changes to 6400 (256 times 25) while it is supposed to have dimension 9216 (256 times 36). Here is the error:

ValueError: dimension mismatch in args to gemm (256,6400)x(9216,4096)->(256,4096)
Apply node that caused the error: GpuDot22(GpuFlatten{2}.0, <CudaNdarrayType(float32, matrix)>)
Toposort index: 314
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(256, 6400), (9216, 4096)]
Inputs strides: [(6400, 1), (4096, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuElemwise{Add}[(0, 0)](GpuDot22.0, GpuDimShuffle{x,0}.0)]]

**Comment by gwding** [comment]
@soheilb I would suggest looking at the padding size settings around
https://github.com/uoguelph-mlrg/theano_alexnet/blob/master/lib/layers.py#L172
There might be some subtle difference between the cudnn library and cudaconvnet, on how to use those settings.
Sorry that I personally don't have easy access on machines that can run these things, so couldn't try it myself.

**Comment by soheilb** [comment]
Yes, it seems the difference is in how they handle the padding. Thanks for looking into this.
