### ISSUE TITLE
meta data files

### ISSUE THREAD

**Issue by srp1970** [uoguelph-mlrg/theano_alexnet#21]
I see that we need to have several meta data files listed in paths.yaml like

meta_clsloc_mat: '/mnt/data/datasets/lsvrc_2014/ILSVRC2014_devkit/data/meta_clsloc.mat'
val_label_file: '/mnt/data/datasets/lsvrc_2014/ILSVRC2014_devkit/data/ILSVRC2014_clsloc_validation_ground_truth.txt'

valtxt_filename: '/scratch/ilsvrc12/misc/val.txt'
traintxt_filename: '/scratch/ilsvrc12/misc/train.txt'

Can  you please provide these meta data files or point me to the location where we can download these? I have downloaded imagenet images from imagenet site, but do not know where to get these from.

For caffe/torch, these are generated by some scripts.

Prakash

**Comment by hma02** [comment]
Hi @srp1970 ,

The development kit folder can be downloaded from ImageNet website.

In the main site, click on download.

Then go to "download original images" and log in with your user name and password. (The registration is free for learning usage)

Then click on the link under "Download links to ILSVRC2014 image data" which will bring you to the site of all competition resources including the development kit.

Those paths in the  paths.yaml file follow the folder structure inside the downloaded tar file.
