### ISSUE TITLE
Momentum loading

### ISSUE THREAD

**Issue by am-gill** [uoguelph-mlrg/theano_alexnet#22]
When loading the saved state of the network, momentum is loaded for from one epoch higher than the loaded epoch

**Comment by gwding** [comment]
thanks for pointing this out. I myself do not have easy access to machines that can run this. Do you think this would be an easy fix? and can submit a pull request? thanks!

**Comment by hma02** [comment]
@asgill 
The bug is caused by this line:
https://github.com/uoguelph-mlrg/theano_alexnet/blob/master/train.py#L92

You can fix this by moving this line after

`
load_momentums(vels, config['weights_dir'], epoch)
`
Also replace `epoch`  in the `load_momentums` arguments to `load_epoch`.

**Comment by gwding** [comment]
@hma02 thanks for looking into this! can u do a quick pull request?

**Comment by hma02** [comment]
@gwding 
just get a chance to fix this, see #24
