### ISSUE TITLE
Validate Performance

### ISSUE THREAD

**Issue by ksarker1205** [uoguelph-mlrg/theano_alexnet#25]
What does 'validate_performance.py' script do ? Does it run classification ?

**Comment by gwding** [comment]
@ksarker1205 it runs but does not output the classification predictions, you might want to look at the following lines to see how to modify it to do so.
https://github.com/uoguelph-mlrg/theano_alexnet/blob/master/lib/layers.py#L278
https://github.com/uoguelph-mlrg/theano_alexnet/blob/master/alex_net.py#L128
https://github.com/uoguelph-mlrg/theano_alexnet/blob/master/alex_net.py#L225
