### ISSUE TITLE
Trained model file

### ISSUE THREAD

**Issue by erfannoury** [uoguelph-mlrg/theano_alexnet#3]
Hello
Are you going to make the trained model available for use?

**Comment by gwding** [comment]
Hi, 
Thanks for the interest. I'll be working on this and let you know in about a week.

**Comment by yassersouri** [comment]
We are looking forward to this.

**Comment by gwding** [comment]
Hi, sorry for the delay. The trained model can be found at pretrained/alexnet/readme.md now.

**Comment by erfannoury** [comment]
Thank you for providing the trained model. It is much appreciated.

**Comment by yassersouri** [comment]
@gwding Thanks, :+1:
