### ISSUE TITLE
Other datasets.

### ISSUE THREAD

**Issue by gasiort** [uoguelph-mlrg/theano_alexnet#7]
Does it work with ILSVRC 2010 dataset?

**Comment by gwding** [comment]
i'm not exactly sure whether it'll work. But from these webpages
http://image-net.org/challenges/LSVRC/2012/
http://www.image-net.org/challenges/LSVRC/2011/
http://www.image-net.org/challenges/LSVRC/2010/

It seems that the training data are the same for 2010 and 2012. If it's not the case, files in the preprocessing folder might need to be modified slightly.

**Comment by gasiort** [comment]
I havent tracked your code in detail but while running on LSVRC2010 I get this error:

Traceback (most recent call last):
  File "make_train_val_txt.py", line 34, in <module>
    dict_train_id = {wnid: dict_wnid_to_origid[wnid] for wnid in sorted_train_dirs}
  File "make_train_val_txt.py", line 34, in <dictcomp>
    dict_train_id = {wnid: dict_wnid_to_origid[wnid] for wnid in sorted_train_dirs}
KeyError: 'n01484850'
Traceback (most recent call last):
  File "make_labels.py", line 121, in <module>
    save_val_labels(misc_dir, val_label_name)
  File "make_labels.py", line 100, in save_val_labels
    with open(os.path.join(misc_dir, 'val.txt'), 'r') as text_labels:
IOError: [Errno 2] No such file or directory: '/media/tomasz/DATA/DATA/workspace/UndergradProject/imagenet_pre/misc/val.txt'

**Comment by ScutZB** [comment]
I also found this problem when I tried to do training using ILSVRC2012 a few days ago.
To solve this problem, I changed the file "make_train_val_txt.py" as follows:
line 29-30:
`synsets_wnid = [str(synset[0][1][0]) for synset in synsets]`
`dict_wnid_to_origid = {`
`str(synset[0][1][0]): int(synset[0][0][0]) for synset in synsets}`
and it works fine.
It seems that the format of file "meta.mat" is slightly different in this dataset.
