### ISSUE TITLE
Will train.py end itself?

### ISSUE THREAD

**Issue by duguyue100** [uoguelph-mlrg/theano_alexnet#8]
Hi,

I'm playing with your code and so far it's working nicely in training.

However, after I got the message "Optimization Complete", the program is hanging there.
Shall I quit it directly? or it's running some other operations?
I noticed my CPU usage and GPU temperature are back at normal stage. 

Regards,
Hu Yuhuang.

**Comment by duguyue100** [comment]
Never mind, stupid question.

I saw you have a endless loop in `proc_load.py`.

Another question, is this `proc_load.py` setting up a tcp port so that it can load new data?

**Comment by gwding** [comment]
yes, there is an endless loop. My apology.

the tcp is only used once for passing the inter-process communication handle (IPCMemoryHandle), which is used in each update to share memory between processes.

**Comment by duguyue100** [comment]
So it's safe to say I can simply terminate it after training?

**Comment by gwding** [comment]
yes, that's correct. If I have time to fix this infinite loop, I'll let you know.

**Comment by duguyue100** [comment]
Thanks for your answer.
