### ISSUE TITLE
Results from intermediate stages from ConvPoolLayer

### ISSUE THREAD

**Issue by tumble-weed** [uoguelph-mlrg/theano_alexnet#9]
Hi any suggestions on how i can obtain the outputs from the convolution-pre-nonlinearity, the nonlinearity, the normalization steps individually?

**Comment by gwding** [comment]
In train.py line 50, the model is defined. You actually have access to all the layers in model.layers, which is a list.
for the layer you want to compute, you can compile a new function using model.layers[i].output as the output of a theano function.

**Comment by oogilyboogily** [comment]
yes bu each layer is a composite conv+pool+norm operation, my question is how can i get the result after conv but before pool say.

upon using the python inbuilt dir on an element of this list i get:
['W', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'b', 'channel', 'convstride', 'filter_shape', 'filter_size', 'image_shape', 'lib_conv', 'lrn', 'output', 'padsize', 'params', 'poolsize', 'poolstride', 'weight_type']

it would seem that such an intermediate result is not directly accessible from a layer object?

**Comment by gwding** [comment]
I see, in that case I suggest you do something like self.conv_out =
conv_out in the ConvPoolLayer, then you should have that attribute
available.

But be aware that the cudaconvnet and cudnn might have some difference in
the convlayer.

**Comment by tumble-weed** [comment]
Yeah it worked. thanks.
